version: '3.8'

services:
  # Redis缓存服务 (开发环境)
  redis:
    image: redis:7-alpine
    container_name: ip-query-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 后端API服务 (开发模式)
  backend:
    build:
      context: ./backend-fastapi
      dockerfile: Dockerfile
    container_name: ip-query-backend-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=sqlite:///./data/app.db
      - DEBUG=true
      - RELOAD=true
    volumes:
      - ./backend-fastapi:/app
      - ./backend-fastapi/data:/app/data
    depends_on:
      redis:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

networks:
  default:
    name: ip-query-dev-network
